name: 'Verify'

on:
  push:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
      - name: Format
        run: dotnet format --verify-no-changes
      - name: Build
        run: dotnet build -warnaserror
      - name: Test
        run: dotnet test
